[".config/k9s/skins"]
type            = "archive"
url             = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
include         = ["k9s-main/dist/**"]
stripComponents = 2
refreshPeriod   = "168h"

[".local/share/tmux/plugins/tpm"]
type      = "git-repo"
url       = "https://github.com/tmux-plugins/tpm"
pull.args = ["--ff-only"]

[".local/src/neovim"]
type      = "git-repo"
url       = "https://github.com/neovim/neovim.git"
pull.args = ["--ff-only", "--force"]

[".local/src/typeshed"]
type      = "git-repo"
url       = "https://github.com/python/typeshed.git"
pull.args = ["--ff-only"]

["./Projects/nvim/conform.nvim"]
type      = "git-repo"
url       = "https://github.com/William-Blackie/conform.nvim"
pull.args = ["--ff-only"]

["./Projects/nvim/nvim-lspconfig"]
type      = "git-repo"
url       = "https://github.com/William-Blackie/nvim-lspconfig"
pull.args = ["--ff-only"]

["./Projects/nvim/grove.nvim"]
type      = "git-repo"
url       = "https://github.com/William-Blackie/grove.nvim"
pull.args = ["--ff-only"]

["./Projects/nvim/neotest-python"]
type      = "git-repo"
url       = "https://github.com/William-Blackie/neotest-python.git"
pull.args = ["--ff-only"]

["./Projects/nvim/nvim-lint"]
type      = "git-repo"
url       = "https://github.com/William-Blackie/nvim-lint"
pull.args = ["--ff-only"]
